name: Deploy Server to AWS

on:
  release:
    types: [created]
  push:
    branches: ['master']
  

env:
  AWS_REGION: us-east-2
  APP_COMPONENT: server
  APPLICATION_NAME: purdue-geochallenge-server
  ENVIRONMENT_NAME: Purduegeochallengeserver-env

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./${{ env.APP_COMPONENT }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - run: ./scripts/create_env.sh
      shell: bash
      env:
        MONGODB_CONNECTION_URL: ${{secrets.MONGODB_CONNECTION_URL}}
        MONGODB_PORT: ${{secrets.MONGODB_PORT}}

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
        application_name: ${{ env.APPLICATION_NAME }}
        environment_name: ${{ env.ENVIRONMENT_NAME }}
        
        version_label: ${{ github.event.release.name || github.event.head_commit.id }}
        region: ${{ env.AWS_REGION }}
        deployment_package: ./${{ env.APP_COMPONENT }}/deploy.zip
