name: Deploy Client to AWS

on:
  push:
    branches:
      - 'releases/**'
      - 'github_action_test'

env:
  AWS_REGION: us-east-2
  APP_COMPONENT: client
  APPLICATION_NAME: purdue-geochallenge-client
  ENVIRONMENT_NAME: Purduegeochallengeclient-env

permissions:
  contents: read

jobs:

  upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ env.APP_COMPONENT }}
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: testwebhostkatpu
          source_dir: './client/build'
