name: Deploy Client to AWS

on:
  push:
    branches:
      - 'releases/**'
      - 'github_action_test'

env:
  AWS_REGION: us-east-2
  APP_COMPONENT: client
  APPLICATION_NAME: purdue-geochallenge-client
  ENVIRONMENT_NAME: Purduegeochallengeclient-env

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./${{ env.APP_COMPONENT }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
    
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
        application_name: ${{ env.APPLICATION_NAME }}
        environment_name: ${{ env.ENVIRONMENT_NAME }}
        
        version_label: ${{ github.event.head_commit.id }}
        region: ${{ env.AWS_REGION }}
        deployment_package: ./${{ env.APP_COMPONENT }}/deploy.zip
