name: Deploy Server to AWS

on:
  push:
    branches: ['katherine-mich-s2']
  pull_request:
    types: [opened, reopened]

env:
  APP_COMPONENT: server

permissions:
  contents: read

jobs:
  test:
    name: Unit Tests for Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ env.APP_COMPONENT }}

    steps:
    - uses: actions/checkout@v3
    - name: Pull Secrets from Github Secrets
      run: ./scripts/create_env.sh
      shell: bash
      env:
        MONGODB_CONNECTION_URL: ${{secrets.MONGODB_CONNECTION_URL}}
        MONGODB_PORT: ${{secrets.MONGODB_PORT}}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Install modules
      run: yarn
    - name: Run Jest Unit tests
      run: yarn test
